### ISSUE TITLE
time-out issue

### ISSUE THREAD

**Issue by DmytroT** [api-ai/api-ai-android-sdk#20]
We are trying to implement a test with your solution but we are encountering some road blocks. There is a content time-out/error (“Speech recognition engine error: No recognition result matched.”) when waiting for voice command, even if it is just 1-2 seconds. 

Sample app has the same issue - https://github.com/api-ai/api-ai-android-sdk/tree/master/apiAISampleApp

Any suggestions?

**Comment by xVir** [comment]
Hi, @DmytroT 
Do you use System recognition? 
It seems it is temporary problem in Google [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer.html), so, we can only wait until the problem will be fixed...

Thanks.

**Comment by DmytroT** [comment]
hi @xVir, 
right, I use System recognition.
I just tried to use Spektoit and it works better.

Thanks!

**Comment by xVir** [comment]
Hi, @DmytroT 

Thanks for the inforamtion.
Also, I think the issue should be fixed soon by Google.

Thanks!

**Comment by smidaharoun** [comment]
Any updates about this issue? I'm still having the same problem.

**Comment by xVir** [comment]
Hi, @smidaharoun 
What version of Android do you use? 

Thanks!

**Comment by smidaharoun** [comment]
The latest one (25). Is there a difference ?

**Comment by xVir** [comment]
This problem could be related to specific Google SpeechRecognizer version. So, I will try to check it on our devices.

Thanks!

**Comment by smidaharoun** [comment]
I've tried it with other versions (19, 20, 23) and still the same problem.

**Comment by xVir** [comment]
@smidaharoun 
Could you please attach parts of your code that uses the SDK and log with error message?

Thanks!
